In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

data_1 = pd.read_csv('../data/creditcard.csv')
data_1.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [7]:
# https://www.kaggle.com/datasets/dhanushnarayananr/credit-card-fraud

data_2 = pd.read_csv('../data/card_transdata.csv')
data_2.columns

Index(['distance_from_home', 'distance_from_last_transaction',
       'ratio_to_median_purchase_price', 'repeat_retailer', 'used_chip',
       'used_pin_number', 'online_order', 'fraud'],
      dtype='object')

In [8]:
data_2

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [9]:
# https://catalog.data.gov/dataset/consumer-complaint-database

data_3 = pd.read_csv('../data/complaints.csv')
data_3.columns

/var/folders/xg/5n69np453nn3pzzpyw20jrp40000gn/T/ipykernel_82466/506852709.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  data_3 = pd.read_csv('../data/complaints.csv')

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [11]:
data = data_3.drop(['Consumer consent provided?', 'Sub-product', 'Issue', 'Consumer complaint narrative', 'Date received', 'Complaint ID', 'ZIP code', 'Date sent to company' ,'Company response to consumer', 'Company public response'], axis=1)
# data = pd.get_dummies(data)
data

,Product,Sub-issue,Company,State,Tags,Submitted via,Timely response?,Consumer disputed?
0,Credit card,Was not notified of investigation status or re...,Experian Information Solutions Inc.,TX,NaN,Web,Yes,NaN
1,Credit reporting or other personal consumer re...,Account information incorrect,AMERICAN EXPRESS COMPANY,NJ,NaN,Web,Yes,NaN
2,Credit card,Information belongs to someone else,TRUIST FINANCIAL CORPORATION,TX,Older American,Web,Yes,NaN
3,Debt collection,Didn't receive notice of right to dispute,ENCORE CAPITAL GROUP INC.,NY,NaN,Web,Yes,NaN
4,Credit card,Problem with fees,Atlanticus Services Corporation,NY,NaN,Referral,Yes,NaN
...,...,...,...,...,...,...,...,...
4838840,"Credit reporting, credit repair services, or o...",Information belongs to someone else,"EQUIFAX, INC.",TX,NaN,Web,Yes,NaN
4838841,"Payday loan, title loan, or personal loan",NaN,NBT BANCORP INC.,NJ,NaN,Phone,Yes,NaN
4838842,Mortgage,NaN,Chesmar Homes,TX,NaN,Web,Yes,NaN
4838843,"Credit reporting, credit repair services, or o...",Reporting company used your report improperly,"EQUIFAX, INC.",GA,NaN,Web,Yes,NaN
4838844,"Payday loan, title loan, or personal loan",NaN,Flandreau Santee Sioux Tribe,TX,NaN,Web,Yes,NaN